language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

arch:
  - amd64

before_install:
  - pip install -r requirements.txt

script:
  - pytest
  - pytest --cov=adventure_bot tests

before_deploy:
  - pyinstaller --onefile bot.py
  - cp ./dist/bot.exe bot.exe

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file:
    - "bot.exe"
    - "db.json"
    - ".env"
  edge: true
  on:
    tags: true
