language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

arch:
  - amd64

services:
  - docker

before_install:
  - pip install -r requirements.txt

script:
  - python -m unittest discover tests
  - coverage run -m unittest discover

before_deploy:
  - pyinstaller --onefile bot.py

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: "./dist/bot.exe"
  edge: true
  on:
    tags: true
